In [ ]:
import numpy as np

In [ ]:
 
 import numpy as np
 
array=np.zeros(10)
 
print("An array of 10 zeros:")
 
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
 import numpy as np
array=np.ones(10)
 
print("An array of 10 ones:")
 
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
 import numpy as np
array=np.ones(10)*5
 
print("An array of 10 fives:")
 
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
 
import numpy as np
 
array=np.arange(10,51)
 
print("Array of the integers from 10 to50")
 
print(array)

Array of the integers from 10 to50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
 
import numpy as np
 
array=np.arange(10,51,2)
 
print("Array of all the even integers from 10 to 50")
 
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
 
import numpy as np
 
x =  np.arange(0, 9).reshape(3,3)
 
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
 
import numpy as np
 
array_2D=np.identity(3)
 
print('3x3 matrix:')
 
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
 
import numpy as np
 
array = np.linspace(0,1,20)
 
print(array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
 
import numpy as np
 
array= np.arange(1,26).reshape(5,5)
 
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np
array[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
import numpy as np
array[3,4]

20

In [ ]:
import numpy as np
array[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
import numpy as np
array[4:,0:4]

array([[21, 22, 23, 24]])

In [ ]:
import numpy as np
array[3:,0:4]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
import numpy as np
array.sum()

325

In [ ]:
import numpy as np
array.std()

7.211102550927978

In [ ]:
import numpy as np
array.sum(axis=0)

array([55, 60, 65, 70, 75])